// Renders the site's own content into README.md. The two are different targets
// and their reference prose is written separately on purpose, but everything
// the site says about itself lives in site/code-samples.mjs and everything it
// says about the CLI is generated by running the CLI, so neither has a second
// copy here. This script pastes both into the regions the README marks, and
// tests/readme.test.ts fails when the README no longer matches.
import { readFileSync, writeFileSync } from 'node:fs';

import { renderCliReference } from '../site/cli-reference.mjs';
import {
  agents,
  cd,
  copy,
  examples,
  install,
  prompt,
  samples,
  setupPrompt,
  terminals,
  trees,
} from '../site/code-samples.mjs';

const README = new URL('../README.md', import.meta.url);

/** A fenced block. No sample contains a fence, so three backticks are enough. */
const fence = (lang, text) => '```' + lang + '\n' + text + '\n```';

/** A snippet under the filename it belongs in, the way the site labels its panels. */
const labeled = (file, name) => `\`${file}\`\n\n${fence(samples[name].lang, samples[name].code)}`;

/** The README hard-wraps its prose, and a generated paragraph has to look the same. */
function wrap(text, width = 92) {
  const lines = [];
  let line = '';
  for (const word of text.split(' ')) {
    if (line && line.length + 1 + word.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = line ? `${line} ${word}` : word;
    }
  }
  if (line) lines.push(line);
  return lines.join('\n');
}

function renderExample({ title, note, tree, file, sample, terminal }) {
  const blocks = [`### ${title}`, wrap(note)];
  if (tree) blocks.push(fence('text', trees[tree]));
  blocks.push(labeled(file, sample));
  if (terminal) blocks.push(fence('text', terminals[terminal]));
  return blocks.join('\n\n');
}

/**
 * The install card, which cycles the harness name on the site. Markdown cannot
 * cycle, so the alternatives ride along as a comment on the line they replace.
 */
function renderInstall() {
  const [first, ...rest] = agents;
  return [
    `### ${copy.install.heading}`,
    fence(
      'sh',
      [install, cd, `${first} "${prompt}"`.padEnd(46) + `# or ${rest.join(', ')}`].join('\n'),
    ),
  ].join('\n\n');
}

function renderCommands() {
  return renderCliReference()
    .map((entry) => `### ${entry.command}\n\n${fence('text', entry.transcript)}`)
    .join('\n\n');
}

/** Marker id to the markdown it stands for. */
const generated = {
  // Bold, so a lone sentence under the title reads as the tagline it is.
  tagline: `**${copy.tagline}**`,
  hero: [labeled('agent-reference.json', 'shared'), fence('text', terminals.session)].join('\n\n'),
  agent: [`### ${copy.agent.heading}`, fence('text', setupPrompt), wrap(copy.agent.note)].join(
    '\n\n',
  ),
  install: renderInstall(),
  examples: examples.map(renderExample).join('\n\n'),
  commands: [wrap(copy.commands.note), renderCommands()].join('\n\n'),
};

export function render(readme) {
  const seen = new Set();
  const rendered = readme.replace(
    /<!-- generated:(\S+) -->[\s\S]*?<!-- \/generated -->/g,
    (_match, id) => {
      if (!(id in generated)) throw new Error(`README marks a region '${id}' that nothing renders`);
      seen.add(id);
      return `<!-- generated:${id} -->\n${generated[id]}\n<!-- /generated -->`;
    },
  );

  const missing = Object.keys(generated).filter((id) => !seen.has(id));
  if (missing.length) throw new Error(`README has no region for: ${missing.join(', ')}`);
  return rendered;
}

export function readReadme() {
  return readFileSync(README, 'utf8');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const before = readReadme();
  const after = render(before);
  if (after === before) {
    console.log('README.md is already in sync');
  } else {
    writeFileSync(README, after);
    console.log('README.md updated from the site');
  }
}
